apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: aso-teamgg-rg
  namespace: team-gg
spec:
  location: uksouth


---
apiVersion: managedidentity.azure.com/v1api20181130
kind: UserAssignedIdentity
metadata:
 name: teamaaauserassignedidentity
 namespace: team-gg
spec:
 location: uksouth
 owner:
   name: aso-teamgg-rg