apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: aso-teamaa-rg
  namespace: team-aa
spec:
  location: uksouth


---
apiVersion: managedidentity.azure.com/v1api20181130
kind: UserAssignedIdentity
metadata:
 name: teamaauserassignedidentity
 namespace: team-aa
spec:
 location: uksouth
 owner:
   name: aso-teamaa-rg